name: Publish to pub.dev

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
      - run: flutter pub get
      - run: flutter test
      - name: 🔑 Authenticate with pub.dev
        env:
          PUB_DEV_CREDENTIALS: ${{ secrets.PUB_DEV_CREDENTIALS }}
        run: |
          mkdir -p ~/.config/dart
          echo "$PUB_DEV_CREDENTIALS" > ~/.config/dart/pub-credentials.json
      - name: 📢 Publish
        run: dart pub publish --force
